CREATE TABLE issue
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number        INTEGER                                 NOT NULL,
    is_reported   BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    repository_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_issue PRIMARY KEY (id)
);

CREATE TABLE repository
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner     VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_repository PRIMARY KEY (id)
);

ALTER TABLE repository
    ADD CONSTRAINT uc_402a09c40104badcfd93eb18d UNIQUE (owner, name);

ALTER TABLE issue
    ADD CONSTRAINT uc_82333b7769500e1d175ec4729 UNIQUE (number, repository_id);

ALTER TABLE issue
    ADD CONSTRAINT FK_ISSUE_ON_REPOSITORY FOREIGN KEY (repository_id) REFERENCES repository (id);
